"""
真实物理参数边界配置文件（修正版）
"""

USE_KUKA = False
TARGET_END_POS = [0.25, 0.0, 0.6]

MASS_OFFSET_RANGE = 0.20
JOINT_DAMPING_RANGE = 0.30
FRICTION_COEFF_RANGE = 0.05
COMM_DELAY_RANGE = 5

NUM_RANDOM_TESTS = 50
MOVE_SPEED = 15
CONTROL_FORCE = 120.0
VERBOSE = True
